name: Windows

on: [push]

env:
  PHP_EXT: zstd
  BIN_SDK_VER: 2.3.0

jobs:
  ci:
    strategy:
      matrix:
        php:
          - '8.4'
          - '8.3'
          - '8.2'
          - '8.1'
        arch:
          - x64
          - x86
        ts:
          - 'nts'
          - 'ts'
        vs:
          - vs16
          - vs17
        library:
          - false
          - true
        apcu:
          - ''
          - 'apcu'
        exclude:
          - php: '8.4'
            vs: vs16
          - php: '8.4'
            vs: vs17
            apcu: 'apcu' # Doesn't exist
          - php: '8.3'
            vs: vs17
          - php: '8.2'
            vs: vs17
          - php: '8.1'
            vs: vs17

    runs-on: ${{ matrix.vs == 'vs17' && 'windows-2022' || 'windows-2019' }}

    env:
      PHP_VER: ${{ matrix.php }}
      PECL_APCU: ${{ matrix.apcu }}
      VS: ${{ matrix.vs }}
      ARCH: ${{ matrix.arch }}
      TS: ${{ matrix.ts }}

    if: contains(github.event.head_commit.message, 'ci skip') == false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout submodule
        run: .\.github\workflows\submodule.ps1
        if: ${{ ! matrix.library }}
      - name: Install dependency library
        run: .\.github\workflows\vcpkg.ps1
        env:
          VCPKG_LIBRARY: zstd
        if: ${{ matrix.library }}

      - uses: actions/cache@v4
        with:
          path: |
            C:\php\php-*.zip
          key: ${{ runner.os }}-php

      - name: Install build command
        run: .\.github\workflows\install.ps1

      - name: Build
        run: .\.github\workflows\build.ps1

      - name: Test
        run: .\.github\workflows\test.ps1
        env:
          REPORT_EXIT_STATUS: 1
          NO_INTERACTION: 1

      - name: Store artifact DLL
        uses: actions/upload-artifact@v4
        with:
          name: php_${{ env.PHP_EXT }}-${{ matrix.php }}-${{ matrix.ts }}-${{ matrix.vs }}-${{ matrix.arch }}
          path: .\php_${{ env.PHP_EXT }}.dll
          overwrite: true
        if: ${{ ! matrix.library && matrix.apcu == '' }}
